-- 1. ENUM 타입 정의 (주문 상태 등)
CREATE TYPE order_status_type AS ENUM ('PENDING', 'COOKING', 'READY', 'COMPLETED', 'CANCELED');
CREATE TYPE stock_status_type AS ENUM ('IN_STOCK', 'OUT_OF_STOCK', 'LIMITED');

-- 2. 식당 (Cafeterias) - 매니저보다 먼저 생성
CREATE TABLE public.cafeterias (
  cafeteria_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  status VARCHAR(50) DEFAULT 'OPEN', -- OPEN, CLOSED, BREAK
  location VARCHAR(255),
  operating_hours VARCHAR(100),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. 매니저 (Managers) - Supabase Auth와 연동
-- manager_id는 auth.users의 uuid를 참조하도록 설정 (UUID 사용 추천)
CREATE TABLE public.managers (
  manager_id UUID REFERENCES auth.users(id) PRIMARY KEY,
  cafeteria_id BIGINT REFERENCES public.cafeterias(cafeteria_id),
  name VARCHAR(100) NOT NULL,
  phone_number VARCHAR(20),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. 고객 (Customers) - Supabase Auth와 연동
CREATE TABLE public.customers (
  customer_id UUID REFERENCES auth.users(id) PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  name VARCHAR(100),
  phone_number VARCHAR(20),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. 메뉴 (Menus)
CREATE TABLE public.menus (
  menu_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cafeteria_id BIGINT REFERENCES public.cafeterias(cafeteria_id) NOT NULL,
  menu_name VARCHAR(255) NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  description TEXT,
  image_url VARCHAR(255),
  stock_status stock_status_type DEFAULT 'IN_STOCK',
  daily_limit INTEGER DEFAULT 100, -- 일일 한정 수량 추가 제안
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. 주문 (Orders)
CREATE TABLE public.orders (
  order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id UUID REFERENCES public.customers(customer_id) NOT NULL,
  cafeteria_id BIGINT REFERENCES public.cafeterias(cafeteria_id) NOT NULL,
  order_status order_status_type DEFAULT 'PENDING',
  total_amount DECIMAL(10, 2) NOT NULL,
  payment_method VARCHAR(50) NOT NULL, -- CARD, SIMPLE_PAY etc.
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. 주문 상세 (Order Details)
CREATE TABLE public.order_details (
  order_detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES public.orders(order_id) ON DELETE CASCADE,
  menu_id BIGINT REFERENCES public.menus(menu_id),
  quantity INTEGER NOT NULL,
  unit_price DECIMAL(10, 2) NOT NULL, -- 주문 시점의 가격 박제
  subtotal DECIMAL(10, 2) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. 통계 (Sales) - JSONB 활용
CREATE TABLE public.sales (
  sales_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cafeteria_id BIGINT REFERENCES public.cafeterias(cafeteria_id),
  sales_date DATE NOT NULL,
  total_orders INTEGER DEFAULT 0,
  total_sales DECIMAL(15, 2) DEFAULT 0,
  menu_sales_data JSONB, -- { "menu_A": 10, "menu_B": 5 } 형식으로 저장
  hourly_sales_data JSONB, -- { "09:00": 50000, "10:00": 20000 }
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. 알림 (Notifications)
CREATE TABLE public.notifications (
  notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id UUID REFERENCES public.customers(customer_id),
  order_id BIGINT REFERENCES public.orders(order_id),
  message TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
